language: php
php:
  - '7.1'

install:
  - composer install --prefer-dist --optimize-autoloader --no-interaction

notifications:
  email:
    recipients:
      - DavidNineRoc@gmail.com
    on_success: never
    on_failure: always

before_script:
  - git --version
  - php -v
  - composer --version
  - phpunit --version
script:
  - vendor/bin/phpunit