#!/usr/bin/env php
<?php

use Waitmoonman\Database\DB;

require 'vendor/autoload.php';

// 初始化数据库连接
DB::addConnection(require __DIR__ . '/config/database.php');

// 构造查询条件
$users = DB::table('users')
    ->listenSql(
        function($sql, $params, $realSql){
            // do something
            var_dump($realSql);
        }
        , true
    )
    ->where('id', '>' ,10)
    ->where('login_count', 0)
    ->delete();

var_dump($users);