#!/usr/bin/env php
<?php

use Waitmoonman\Database\DB;

require 'vendor/autoload.php';

// 初始化数据库连接
DB::addConnection(require __DIR__ . '/config/database.php');

// 构造查询条件
$users = DB::table('users')
    ->listenSql(
            function($sql, $params, $realSql){
                // do something
                var_dump($realSql);
            }
            , true
    )
    ->select('id', 'name', 'sex')
    ->where('id', '>' ,1)
    ->update(['login_count' => 3, 'name' => 'david']);

var_dump($users);